service: featHashLicensesManager

provider:
  name: aws
  runtime: nodejs8.10
  memorysize: 128
  timeout: 10
  stage: prod
  region: us-east-1
functions:
  check:
    handler: handler.check
    events:
      - http:
          path: licensesControl/check
          method: post
          cors: true
  activate:
    handler: handler.activate
    events:
     - http:
         path: licensesControl
         method: put
         cors: true
  deactivateOne:
    handler: handler.deactivateOne
    events:
     - http:
         path: licensesControl/{rigName}
         method: delete
         cors: true
  deactivateAll:
    handler: handler.deactivateAll
    events:
     - http:
         path: licensesControl
         method: delete
         cors: true
  getUpdate:
      handler: handler.getUpdate
      events:
        - http:
            path: licensesControl
            method: post
            cors: true
  getDBUpdates:
      handler: handler.getDBUpdates
      events:
        - schedule: rate(24 hours)

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: featcash.com
    certificateName: 'featcash.com'
    basePath: ""
    stage: prod
    createRoute53Record: true